[project]
name = 'service-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.service-marketplace]
path = 'contracts/service-marketplace.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
